import unittest

from tests.ServerFunctional import ServerFullInitalValues


from tests.ServiceGroupFunctional import ServiceGrouptFullInitialValues
from tests.ServiceFunctional import ServiceFullInitialValues
from tests.LBVserverFunctional import LBVserverFullInitialValues
from tests.LBMonitorFunctional import LBMonitorFullInitialValues
from tests.CSPolicyFunctional import CSPolicyFullInitialValues
from tests.CSActionFunctional import CSActionFullInitialValues
from tests.CSVserverFunctional import CSVserverFullInitialValues
from tests.SSLCertkeyFunctional import SSLCertkeyFullInitialValues


from tests.ServiceGroupFunctional import ServiceGroupMissingArguments
from tests.ServiceFunctional import ServiceMissingArguments
from tests.CSActionFunctional import CSActionMissingArguments
from tests.CSPolicyFunctional import CSPolicyMissingArguments
from tests.CSVserverFunctional import CSVserverMissingArguments
from tests.LBVserverFunctional import LBVserverMissingArguments
from tests.LBMonitorFunctional import LBMonitorMissingArguments



from tests.ServiceGroupFunctional import ServiceGroupDeleteEntity
from tests.ServiceFunctional import ServiceDeleteEntity
from tests.CSActionFunctional import CSActionDeleteEntity
from tests.CSPolicyFunctional import CSPolicyDeleteEntity
from tests.CSVserverFunctional import CSVserverDeleteEntity
from tests.LBVserverFunctional import LBVserverDeleteEntity
from tests.LBMonitorFunctional import LBMonitorDeleteEntity

from tests.LBVserverFunctional import LBVserverSSLCertkeyBindings
from tests.CSVserverFunctional import CSVserverSSLCertkeyBindings

from tests.ServiceFunctional import ServiceMonitorBindings
from tests.ServiceGroupFunctional import ServiceGroupMonitorBindings




if __name__ == '__main__':
    unittest.main()
