resource_map = {
    "citrix_adc_appfw_confidfield" :  "netscaler.adc.appfwconfidfield",
    "citrix_adc_appfw_fieldtype" :  "netscaler.adc.appfwfieldtype",
    "citrix_adc_appfw_global_bindings" :  "netscaler.adc.appfwglobal_bindings",
    "citrix_adc_appfw_htmlerrorpage" :  "netscaler.adc.appfwhtmlerrorpage",
    "citrix_adc_appfw_jsoncontenttype" :  "netscaler.adc.appfwjsoncontenttype",
    "citrix_adc_appfw_learningsettings" :  "netscaler.adc.appfwlearningsettings",
    "citrix_adc_appfw_policylabel": "netscaler.adc.appfwpolicylabel",
    "citrix_adc_appfw_policy": "netscaler.adc.appfwpolicy",
    "citrix_adc_appfw_profile": "netscaler.adc.appfwprofile",
    "citrix_adc_appfw_settings": "netscaler.adc.appfwsettings",
    "citrix_adc_appfw_signatures": "netscaler.adc.appfwsignatures",
    "citrix_adc_appfw_wsdl": "netscaler.adc.appfwwsdl",
    "citrix_adc_appfw_xmlcontenttype": "netscaler.adc.appfwxmlcontenttype",
    "citrix_adc_appfw_xmlerrorpage": "netscaler.adc.appfwxmlerrorpage",
    "citrix_adc_appfw_xmlschema": "netscaler.adc.appfwxmlschema",
    "citrix_adc_cs_action": "netscaler.adc.csaction",
    "citrix_adc_cs_policy": "netscaler.adc.cspolicy",
    "citrix_adc_cs_vserver": "netscaler.adc.csvserver",
    "citrix_adc_dnsnsrec": "netscaler.adc.dnsnsrec",
    "citrix_adc_get_bearer_token": "netscaler.adc.get_bearer_token",
    "citrix_adc_gslb_service": "netscaler.adc.gslbservice",
    "citrix_adc_gslb_site": "netscaler.adc.gslbsite",
    "citrix_adc_gslb_vserver": "netscaler.adc.gslbvserver",
    "citrix_adc_lb_monitor": "netscaler.adc.lbmonitor",
    "citrix_adc_lb_vserver": "netscaler.adc.lbvserver",
    "citrix_adc_nsip": "netscaler.adc.nsip",
    "citrix_adc_nspartition": "netscaler.adc.nspartition",
    "citrix_adc_password_reset": "netscaler.adc.password_reset",
    "citrix_adc_save_config": "netscaler.adc.save_config",
    "citrix_adc_server": "netscaler.adc.server",
    "citrix_adc_servicegroup": "netscaler.adc.servicegroup",
    "citrix_adc_service": "netscaler.adc.service",
    "citrix_adc_ssl_certkey": "netscaler.adc.sslcertkey",
    "citrix_adc_sslcipher": "netscaler.adc.sslcipher",
    "citrix_adc_sslcipher_sslciphersuite_binding": "netscaler.adc.sslcipher_sslciphersuite_binding",
    "citrix_adc_sslprofile_sslcipher_binding": "netscaler.adc.sslprofile_sslcipher_binding",
    "citrix_adc_system_file": "netscaler.adc.systemfile",
}

state_map = {
    "add": "present",
    "update": "present",
    "delete": "absent",
    "enable": "enable",
    "disable": "disable",
    "present": "present",
    "absent": "absent",
}
play_level_keys_list = [
    "gather_facts",
    "vars",
    "vars_files",
    "vars_prompt",
    "roles",
    "import_playbook",
    "import_tasks",
    "include_tasks",
    "tags",
    "strategy",
    "max_fail_percentage",
    "any_errors_fatal",
    "become",
    "become_user",
    "become_method",
    "remote_user",
    "connection",
    "port",
    "serial",
    "environment",
    "module_defaults",
    "vars_plugins",
    "force_handlers",
    "ignore_errors",
    "ignore_unreachable",
    "run_once"
]

task_level_keys_list = [
    "name",
    "delegate_to",
    "action",
    "args",
    "register",
    "when",
    "loop",
    "with_items",
    "with_dict",
    "with_list",
    "with_fileglob",
    "with_sequence",
    "with_subelements",
    "with_together",
    "until",
    "retries",
    "delay",
    "failed_when",
    "changed_when",
    "ignore_errors",
    "any_errors_fatal",
    "delegate_facts",
    "run_once",
    "local_action",
    "environment",
    "tags",
    "notify",
    "check_mode",
    "diff",
    "throttle",
    "async",
    "poll",
    "become",
    "become_user",
    "become_method",
    "block",
    "rescue",
    "always"
]
netscaler_login_specifics = [
    "nsip", "nitro_user", "nitro_pass", "validate_certs", "nitro_protocol"
]
if __name__ == "__main__":
    pass