---
name: Release the ansible collection to Ansible Galaxy and Ansible Automation Hub
on:
  release:
    types: [published]
permissions: read-all
jobs:
  release:
    permissions:
      contents: write
    uses: ansible/team-devtools/.github/workflows/release_collection.yml@c02723dc3189073de778d8a52ac2fb3b517f1e49  # main
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
