---
name: Release the ansible collection to Ansible Galaxy and Ansible Automation Hub
on:
  release:
    types: [published]
permissions: read-all
jobs:
  release:
    permissions:
      contents: write
    uses: ansible/team-devtools/.github/workflows/release_collection.yml@2bfe64c2d145331d803f1ae2f6a10f17f9d696df  # main
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
