---
name: Release the ansible collection to Ansible Galaxy and Ansible Automation Hub
on:
  release:
    types: [published]
permissions: read-all
jobs:
  release:
    permissions:
      contents: write
    uses: ansible/team-devtools/.github/workflows/release_collection.yml@a7f2500fb428f217418c6c39c016319cd76df408  # main
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
